/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrototypeHostPaidPresentationRouteImport } from './routes/prototype/host-paid-presentation'
import { Route as BillsBillIdIndexRouteImport } from './routes/bills/$billId/index'
import { Route as BillsBillIdSummaryRouteImport } from './routes/bills/$billId/summary'
import { Route as BillsBillIdJoinRouteImport } from './routes/bills/$billId/join'
import { Route as BillsBillIdClaimRouteImport } from './routes/bills/$billId/claim'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeHostPaidPresentationRoute =
  PrototypeHostPaidPresentationRouteImport.update({
    id: '/prototype/host-paid-presentation',
    path: '/prototype/host-paid-presentation',
    getParentRoute: () => rootRouteImport,
  } as any)
const BillsBillIdIndexRoute = BillsBillIdIndexRouteImport.update({
  id: '/bills/$billId/',
  path: '/bills/$billId/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsBillIdSummaryRoute = BillsBillIdSummaryRouteImport.update({
  id: '/bills/$billId/summary',
  path: '/bills/$billId/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsBillIdJoinRoute = BillsBillIdJoinRouteImport.update({
  id: '/bills/$billId/join',
  path: '/bills/$billId/join',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsBillIdClaimRoute = BillsBillIdClaimRouteImport.update({
  id: '/bills/$billId/claim',
  path: '/bills/$billId/claim',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/prototype/host-paid-presentation': typeof PrototypeHostPaidPresentationRoute
  '/bills/$billId/claim': typeof BillsBillIdClaimRoute
  '/bills/$billId/join': typeof BillsBillIdJoinRoute
  '/bills/$billId/summary': typeof BillsBillIdSummaryRoute
  '/bills/$billId/': typeof BillsBillIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/prototype/host-paid-presentation': typeof PrototypeHostPaidPresentationRoute
  '/bills/$billId/claim': typeof BillsBillIdClaimRoute
  '/bills/$billId/join': typeof BillsBillIdJoinRoute
  '/bills/$billId/summary': typeof BillsBillIdSummaryRoute
  '/bills/$billId': typeof BillsBillIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/prototype/host-paid-presentation': typeof PrototypeHostPaidPresentationRoute
  '/bills/$billId/claim': typeof BillsBillIdClaimRoute
  '/bills/$billId/join': typeof BillsBillIdJoinRoute
  '/bills/$billId/summary': typeof BillsBillIdSummaryRoute
  '/bills/$billId/': typeof BillsBillIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/login'
    | '/prototype/host-paid-presentation'
    | '/bills/$billId/claim'
    | '/bills/$billId/join'
    | '/bills/$billId/summary'
    | '/bills/$billId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/prototype/host-paid-presentation'
    | '/bills/$billId/claim'
    | '/bills/$billId/join'
    | '/bills/$billId/summary'
    | '/bills/$billId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/login'
    | '/prototype/host-paid-presentation'
    | '/bills/$billId/claim'
    | '/bills/$billId/join'
    | '/bills/$billId/summary'
    | '/bills/$billId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  LoginRoute: typeof LoginRoute
  PrototypeHostPaidPresentationRoute: typeof PrototypeHostPaidPresentationRoute
  BillsBillIdClaimRoute: typeof BillsBillIdClaimRoute
  BillsBillIdJoinRoute: typeof BillsBillIdJoinRoute
  BillsBillIdSummaryRoute: typeof BillsBillIdSummaryRoute
  BillsBillIdIndexRoute: typeof BillsBillIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/host-paid-presentation': {
      id: '/prototype/host-paid-presentation'
      path: '/prototype/host-paid-presentation'
      fullPath: '/prototype/host-paid-presentation'
      preLoaderRoute: typeof PrototypeHostPaidPresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/$billId/': {
      id: '/bills/$billId/'
      path: '/bills/$billId'
      fullPath: '/bills/$billId/'
      preLoaderRoute: typeof BillsBillIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/$billId/summary': {
      id: '/bills/$billId/summary'
      path: '/bills/$billId/summary'
      fullPath: '/bills/$billId/summary'
      preLoaderRoute: typeof BillsBillIdSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/$billId/join': {
      id: '/bills/$billId/join'
      path: '/bills/$billId/join'
      fullPath: '/bills/$billId/join'
      preLoaderRoute: typeof BillsBillIdJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/$billId/claim': {
      id: '/bills/$billId/claim'
      path: '/bills/$billId/claim'
      fullPath: '/bills/$billId/claim'
      preLoaderRoute: typeof BillsBillIdClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  LoginRoute: LoginRoute,
  PrototypeHostPaidPresentationRoute: PrototypeHostPaidPresentationRoute,
  BillsBillIdClaimRoute: BillsBillIdClaimRoute,
  BillsBillIdJoinRoute: BillsBillIdJoinRoute,
  BillsBillIdSummaryRoute: BillsBillIdSummaryRoute,
  BillsBillIdIndexRoute: BillsBillIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
