/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QuickBillRouteImport } from './routes/quick-bill'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UserProfileSplatRouteImport } from './routes/user-profile.$'
import { Route as BillsBillIdIndexRouteImport } from './routes/bills/$billId/index'
import { Route as BillsBillIdClaimRouteImport } from './routes/bills/$billId/claim'
import { Route as BillsBillIdJoinRouteImport } from './routes/bills/$billId/join'
import { Route as BillsBillIdPayRouteImport } from './routes/bills/$billId/pay'
import { Route as BillsBillIdSummaryRouteImport } from './routes/bills/$billId/summary'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickBillRoute = QuickBillRouteImport.update({
  id: '/quick-bill',
  path: '/quick-bill',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileSplatRoute = UserProfileSplatRouteImport.update({
  id: '/user-profile/$',
  path: '/user-profile/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsBillIdIndexRoute = BillsBillIdIndexRouteImport.update({
  id: '/bills/$billId/',
  path: '/bills/$billId/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsBillIdClaimRoute = BillsBillIdClaimRouteImport.update({
  id: '/bills/$billId/claim',
  path: '/bills/$billId/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsBillIdJoinRoute = BillsBillIdJoinRouteImport.update({
  id: '/bills/$billId/join',
  path: '/bills/$billId/join',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsBillIdPayRoute = BillsBillIdPayRouteImport.update({
  id: '/bills/$billId/pay',
  path: '/bills/$billId/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsBillIdSummaryRoute = BillsBillIdSummaryRouteImport.update({
  id: '/bills/$billId/summary',
  path: '/bills/$billId/summary',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/quick-bill': typeof QuickBillRoute
  '/terms': typeof TermsRoute
  '/user-profile/$': typeof UserProfileSplatRoute
  '/bills/$billId/claim': typeof BillsBillIdClaimRoute
  '/bills/$billId/join': typeof BillsBillIdJoinRoute
  '/bills/$billId/pay': typeof BillsBillIdPayRoute
  '/bills/$billId/summary': typeof BillsBillIdSummaryRoute
  '/bills/$billId/': typeof BillsBillIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/quick-bill': typeof QuickBillRoute
  '/terms': typeof TermsRoute
  '/user-profile/$': typeof UserProfileSplatRoute
  '/bills/$billId/claim': typeof BillsBillIdClaimRoute
  '/bills/$billId/join': typeof BillsBillIdJoinRoute
  '/bills/$billId/pay': typeof BillsBillIdPayRoute
  '/bills/$billId/summary': typeof BillsBillIdSummaryRoute
  '/bills/$billId': typeof BillsBillIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/quick-bill': typeof QuickBillRoute
  '/terms': typeof TermsRoute
  '/user-profile/$': typeof UserProfileSplatRoute
  '/bills/$billId/claim': typeof BillsBillIdClaimRoute
  '/bills/$billId/join': typeof BillsBillIdJoinRoute
  '/bills/$billId/pay': typeof BillsBillIdPayRoute
  '/bills/$billId/summary': typeof BillsBillIdSummaryRoute
  '/bills/$billId/': typeof BillsBillIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/login'
    | '/privacy'
    | '/quick-bill'
    | '/terms'
    | '/user-profile/$'
    | '/bills/$billId/claim'
    | '/bills/$billId/join'
    | '/bills/$billId/pay'
    | '/bills/$billId/summary'
    | '/bills/$billId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/privacy'
    | '/quick-bill'
    | '/terms'
    | '/user-profile/$'
    | '/bills/$billId/claim'
    | '/bills/$billId/join'
    | '/bills/$billId/pay'
    | '/bills/$billId/summary'
    | '/bills/$billId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/login'
    | '/privacy'
    | '/quick-bill'
    | '/terms'
    | '/user-profile/$'
    | '/bills/$billId/claim'
    | '/bills/$billId/join'
    | '/bills/$billId/pay'
    | '/bills/$billId/summary'
    | '/bills/$billId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  QuickBillRoute: typeof QuickBillRoute
  TermsRoute: typeof TermsRoute
  UserProfileSplatRoute: typeof UserProfileSplatRoute
  BillsBillIdClaimRoute: typeof BillsBillIdClaimRoute
  BillsBillIdJoinRoute: typeof BillsBillIdJoinRoute
  BillsBillIdPayRoute: typeof BillsBillIdPayRoute
  BillsBillIdSummaryRoute: typeof BillsBillIdSummaryRoute
  BillsBillIdIndexRoute: typeof BillsBillIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-bill': {
      id: '/quick-bill'
      path: '/quick-bill'
      fullPath: '/quick-bill'
      preLoaderRoute: typeof QuickBillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-profile/$': {
      id: '/user-profile/$'
      path: '/user-profile/$'
      fullPath: '/user-profile/$'
      preLoaderRoute: typeof UserProfileSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/$billId/': {
      id: '/bills/$billId/'
      path: '/bills/$billId'
      fullPath: '/bills/$billId/'
      preLoaderRoute: typeof BillsBillIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/$billId/claim': {
      id: '/bills/$billId/claim'
      path: '/bills/$billId/claim'
      fullPath: '/bills/$billId/claim'
      preLoaderRoute: typeof BillsBillIdClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/$billId/join': {
      id: '/bills/$billId/join'
      path: '/bills/$billId/join'
      fullPath: '/bills/$billId/join'
      preLoaderRoute: typeof BillsBillIdJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/$billId/pay': {
      id: '/bills/$billId/pay'
      path: '/bills/$billId/pay'
      fullPath: '/bills/$billId/pay'
      preLoaderRoute: typeof BillsBillIdPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/$billId/summary': {
      id: '/bills/$billId/summary'
      path: '/bills/$billId/summary'
      fullPath: '/bills/$billId/summary'
      preLoaderRoute: typeof BillsBillIdSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  QuickBillRoute: QuickBillRoute,
  TermsRoute: TermsRoute,
  UserProfileSplatRoute: UserProfileSplatRoute,
  BillsBillIdClaimRoute: BillsBillIdClaimRoute,
  BillsBillIdJoinRoute: BillsBillIdJoinRoute,
  BillsBillIdPayRoute: BillsBillIdPayRoute,
  BillsBillIdSummaryRoute: BillsBillIdSummaryRoute,
  BillsBillIdIndexRoute: BillsBillIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
